import Foundation
import Observation

public struct HistoryItem: Codable, Equatable, Identifiable {
    public var id: UUID
    public var expression: String
    public var result: Double
    public init(expression: String, result: Double) {
        id = UUID()
        self.expression = expression
        self.result = result
    }
}

/// The entire user state is persisted together, including the current error.
private struct SavedState: Codable {
    var expression: String = ""
    var history: [HistoryItem] = []
    var memory: Double = 0
    var lastResult: Double?
    var errorMessage: String?
    var showingResult = false
}

@MainActor @Observable
public final class CalculatorStore {
    public var expression: String {
        didSet {
            if expression != oldValue {
                errorMessage = nil
                showingResult = false
                save()
            }
        }
    }
    public private(set) var history: [HistoryItem]
    public private(set) var memory: Double
    public private(set) var lastResult: Double?
    public private(set) var errorMessage: String?
    public private(set) var showingResult: Bool

    @ObservationIgnored private let defaults: UserDefaults
    @ObservationIgnored private let key: String
    @ObservationIgnored private let evaluator = ExpressionEvaluator()

    public init(defaults: UserDefaults = .standard, key: String = "advancedCalculator.state.v1") {
        self.defaults = defaults
        self.key = key
        let state = defaults.data(forKey: key)
            .flatMap { try? JSONDecoder().decode(SavedState.self, from: $0) } ?? SavedState()
        expression = state.expression
        history = Array(state.history.prefix(10))
        memory = state.memory
        lastResult = state.lastResult
        errorMessage = state.errorMessage
        showingResult = state.showingResult
    }

    public func input(_ symbol: String) {
        if showingResult {
            if ["+", "−", "×", "÷", "%"].contains(symbol), let lastResult {
                expression = operand(lastResult)
            } else {
                expression = ""
            }
        }
        expression += symbol
    }

    public func calculate() {
        do {
            let result = try evaluator.evaluate(expression)
            lastResult = result
            errorMessage = nil
            showingResult = true
            history.insert(HistoryItem(expression: expression, result: result), at: 0)
            history = Array(history.prefix(10))
        } catch {
            errorMessage = error.localizedDescription
            showingResult = false
        }
        save()
    }

    public func clear() {
        expression = ""
        lastResult = nil
        errorMessage = nil
        showingResult = false
        save()
    }

    public func deleteLast() {
        if !expression.isEmpty { expression.removeLast() }
        errorMessage = nil
        showingResult = false
        save()
    }

    public func restore(_ item: HistoryItem) {
        expression = item.expression
        errorMessage = nil
        showingResult = false
        save()
    }

    /// Toggle the final number or parenthesized operand. Wrapping negative numbers
    /// keeps binary operators apart, as required by the specification.
    public func toggleSign() {
        if showingResult, let lastResult { expression = operand(lastResult) }
        let text = expression.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !text.isEmpty else { expression = "−"; return }
        // A second tap unwraps the exact form generated by the first tap.
        let chars = Array(text)
        var end = chars.count
        if chars.last == "%" { end -= 1 }
        if end > 0 && chars[end - 1] == ")" {
            var depth = 0
            for i in stride(from: end - 1, through: 0, by: -1) {
                if chars[i] == ")" { depth += 1 }
                if chars[i] == "(" { depth -= 1 }
                if depth == 0 {
                    let prefix = String(chars[..<i])
                    let body = String(chars[(i + 1)..<(end - 1)])
                    let suffix = String(chars[end...])
                    if body.hasPrefix("−") {
                        expression = prefix + String(body.dropFirst()) + suffix
                    } else {
                        expression = prefix + "(−(" + body + "))" + suffix
                    }
                    return
                }
            }
        }
        let pattern = #"(?:[0-9]+(?:[.,][0-9]*)?|[.,][0-9]+)(?:[eE][+\-]?[0-9]+)?%?$"#
        guard let range = text.range(of: pattern, options: .regularExpression) else { return }
        let prefix = String(text[..<range.lowerBound])
        let number = String(text[range])
        if prefix == "−" || prefix == "-" {
            expression = number
        } else {
            expression = prefix + "(−" + number + ")"
        }
    }

    public func addToMemory() { updateMemory(subtract: false) }
    public func subtractFromMemory() { updateMemory(subtract: true) }

    private func updateMemory(subtract: Bool) {
        do {
            let value = try evaluator.evaluate(expression)
            let newMemory = memory + (subtract ? -value : value)
            guard newMemory.isFinite else { throw CalculatorError.nonFiniteResult }
            memory = newMemory
            errorMessage = nil
        } catch { errorMessage = error.localizedDescription }
        save()
    }

    public func recallMemory() {
        if showingResult { expression = "" }
        if expression.isEmpty {
            expression = operand(memory)
        } else {
            let last = expression.last!
            let separator = "+−-×*÷/(".contains(last) ? "" : "×"
            expression += separator + operand(memory)
        }
        errorMessage = nil
        showingResult = false
        save()
    }

    public func clearMemory() { memory = 0; save() }

    private func operand(_ number: Double) -> String {
        let formatted = ExpressionEvaluator.format(number)
        return number < 0 ? "(" + formatted + ")" : formatted
    }

    public func save() {
        let state = SavedState(expression: expression, history: history, memory: memory,
                               lastResult: lastResult, errorMessage: errorMessage,
                               showingResult: showingResult)
        if let data = try? JSONEncoder().encode(state) { defaults.set(data, forKey: key) }
    }
}
